



class carrion_crow (object):
    name = "Carrion Crow"
    category = 1
    maxHealth = 12
    health = 12
    intro1 = "An unusually large crow pecks at a lump of fetid flesh. At" 
    intro2 = "the sight of you, it squawks menacingly, and in an instant,"
    intro3 = "you are assaulted by a flurry of talons and feathers!"
    strength = 2
    dexterity = 4
    intelligence = 1
    vigor = 2
    reflex = 4
    wisdom = 1
    physAttack = 2
    magAttack = 1
    physDefense = 2
    magDefense = 1
    accuracy = 1
    evade = 1
    level = 1
    gold = 6
class frothing_hound (object):
    name = "Frothing Hound"
    category = 1
    maxHealth = 14
    health = 14
    intro1 = "A vicious looking hound snarls in your direction. It paces"
    intro2 = "around you, its foaming maw clenched tightly displaying"
    intro3 = "a rows of jagged, serrated teeth."
    strength = 3
    dexterity = 6
    intelligence = 1
    vigor = 3
    reflex = 3
    wisdom = 1
    physAttack = 2
    magAttack = 1
    physDefense = 2
    magDefense = 1
    accuracy = 1
    evade = 1
    level = 1
    gold = 10
class rat_king (object):
    name = "Rat King"
    category = 1
    maxHealth = 12
    health = 12
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                                |\n||       |     A writhing mass of fur and claws roll from place to place, devouring every living thing that it crosses.   |\n||       |     In an instant, a horde of large rats, entangled by their tails, crashes into you!                          |                \n||       |________________________________________________________________________________________________________________|"
    strength = 2
    dexterity = 5
    intelligence = 1
    vigor = 2
    reflex = 5
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0

class vagabond (object):
    name = "Vagabond"
    category = 2
    maxHealth = 16
    health = 16
    intro1 = "An emaciated figure steps from the shadows. His weathered"
    intro2 = "skin is scarred and his eyes fix upon you with malicious"
    intro3 = "intent. He pulls a rusted dagger as he approaches."
    strength = 6
    dexterity = 4
    intelligence = 1
    vigor = 4
    reflex = 2
    wisdom = 1
    physAttack = 3
    magAttack = 1
    physDefense = 2
    magDefense = 1
    accuracy = 1
    evade = 1
    level = 1
    gold = 12
class mad_heretic (object):
    name = "Mad Heretic"
    category = 2
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                                |\n||       |     A frail man chatters madly in foreign tongues. He bleeds from self-inflicted wounds, and from his blood    |\n||       |     he casts dark magics. He fixes onto you and begins to chant.                                               |                \n||       |________________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class cutthroat (object):
    name = "Cutthroat"
    category = 2
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                                |\n||       |     A menacing criminal cracks a devious grin when he sees you. He draws a wicked knife that is well-worn      |\n||       |     with considerable use. He's spotted his next victim, and he quickly closes in on you!                      |                \n||       |________________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class graverobber (object):
    name = "Graverobber"
    category = 2
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class vile_surgeon (object):
    name = "Vile Surgeon"
    category = 2
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0

class festering_pilgrim (object):
    name = "Festering Pilgrim"
    category = 3
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class pus_of_man (object):
    name = "Pus of Man"
    category = 3
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class bile_beast (object):
    name = "Bile Beast"
    category = 3
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0

class corpse_collector (object):
    name = "Corpse Collector"
    category = 4
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class sin_eater (object):
    name = "Sin Eater"
    category = 4
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0

class infant_deep_one (object):
    name = "Infant Deep One"
    category = 5
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0
class deep_seated_beast (object):
    name = "Deep Seated Beast"
    category = 5
    maxHealth = 15
    health = 15
    intro = "||        ________________________________________________________________________________________________________________\n||       |                                                                                                               |\n||       |     10+1     |\n||       |     8+5                     |                \n||       |_______________________________________________________________________________________________________________|"
    strength = 4
    dexterity = 3
    intelligence = 1
    vigor = 3
    reflex = 2
    wisdom = 1
    physAttack = 2
    magAttack = 0
    physDefense = 2
    magDefense = 0
    accuracy = 0
    evade = 0
    level = 1
    gold = 0


