



def navigate(player):
    location = player.location
    if location == 11 or location == 12 or location == 13 or location == 14 or location == 15:
        woodsIntro()
    elif location == 22 or location == 23 or location == 24 or location == 25:
        streetsIntro()
    elif location == 33 or location == 34 or location == 35:
        dungeonsIntro()
    elif location == 44 or location == 45:
        cryptsIntro()
    elif location == 55:
        ministryIntro()


def woodsIntro():
    print("   ___   ____  _____  ____    _____  ____  _____  ____  ____               __          __    ____      ____    _____      ____ ")
    print("  |@@@\ |@@@@||@@@@@||@@@@\  |@@@@@||@@@@||@@@@@||@@@@||@@@@\             |@@|        |@@|  /@@@@\    /@@@@\  |@@@@@\    /@@@@\  ")
    print("  |@|)@||@|_    |@|  |@( )@|   |@|  |@|     |@|  |@|_  |@| \@\     /@\    |@@|   __   |@@| /@@/\@@\  /@@/\@@\ |@@|\@@\  |@@( \@| ")
    print("  |@@@/ |@@@|   |@|  |@@@@/    |@|  |@@@|   |@|  |@@@| |@|  |@|   <@@@>   |@@|  /@@\  |@@||@@/  \@@||@@/  \@@||@@| \@@|  \@@\    ")
    print("  |@|   |@|     |@|  |@|\@\    |@|  |@|     |@|  |@|   |@|  |@|    \@/    |@@| /@/\@\ |@@||@@\  /@@||@@\  /@@||@@| /@@|   \@@\   ")
    print("  |@|   |@|__   |@|  |@| \@\  _|@|_ |@|     |@|  |@|   |@|_/@/             \@@/@/  \@\@@/  \@@\/@@/  \@@\/@@/ |@@|/@@/ |@\_)@@|  ")
    print("  |@|   |@@@@|  |@|  |@|  \@||@@@@@||@|   |@@@@@||@@@@||@@@@/               \@@/    \@@/    \@@@@/    \@@@@/  |@@@@@/   \@@@@/   ")   
    print("")
    print("                ____________________________________________________________________________________________________      ")
    print("               |                                                                                                    |     ")
    print("               |     The journey to Pergamum takes you through a forest of petrified trees, long-since stripped     |     ")
    print("               |                                                                                                    |     ")
    print("               |     of foliage and life by the dustland. A worn path has been tread through the skeletal woods,    |     ")
    print("               |                                                                                                    |     ")
    print("               |     left by innumerable sorry souls who sought refuge from the great hostilities of the world      |     ")
    print("               |                                                                                                    |     ")
    print("               |     around them. For most, their pilgrimmage was made in vain, and you pass their huttled remains  |     ")
    print("               |                                                                                                    |     ")
    print("               |     where they dropped. But you are steadfast in conviction, and determined in your cause. You     |     ")
    print("               |                                                                                                    |     ")
    print("               |     must reach the city and succeed where the rest of them could not.                              |     ")
    print("               |____________________________________________________________________________________________________|     ")

def streetsIntro():
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("                ____________________________________________________________________________________________________      ")
    print("               |                                                                                                    |     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               |____________________________________________________________________________________________________|     ")

def dungeonsIntro():
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("                ____________________________________________________________________________________________________      ")
    print("               |                                                                                                    |     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               |____________________________________________________________________________________________________|     ")

def cryptsIntro():
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("                ____________________________________________________________________________________________________      ")
    print("               |                                                                                                    |     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               |____________________________________________________________________________________________________|     ")

def ministryIntro():
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("                ____________________________________________________________________________________________________      ")
    print("               |                                                                                                    |     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               ||     ")
    print("               |____________________________________________________________________________________________________|     ")    

def mapMenu1(nav):
    if nav == 11:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ##  ___             |  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|         ")
        print("||         ## | 1 |  /`|       |  ##/| 2 |//.//.//.//.|  ##/| 3 |//.//.//.//.|  ##/| 4 |//.//.//.//.|  ##/| 5 |//.//.//.//.|         ")
        print("||         ##  ```` _\ |__     |  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|         ")
        print("||         ##      /(   ( \    |  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|         ")
        print("||         ##     /)|   /`(\   |  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|         ")
        print("||         ##     \)|   | (/   |  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//..|  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = 1
        print("||")
        print("||                                                  Traveling to Petrified Woods...")
        print("||")
        cont()
        print("||")
        woodsIntro()
    elif nav == 12:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ##  ___             |  ## .___. . . . . . .|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|         ")
        print("||         ## | 1 |  /`|       |  ##.| 2 |. . . . . . |  ##/| 3 |//.//.//.//.|  ##/| 4 |//.//.//.//.|  ##/| 5 |//.//.//.//.|         ")
        print("||         ##  ```` _\ |__     |  ## .```` . . . . . .|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|         ")
        print("||         ##      /(   ( \    |  ##. . . . . . . . . |  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|         ")
        print("||         ##     /)|   /`(\   |  ## . . . . . . . . .|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|         ")
        print("||         ##     \)|   | (/   |  ##. . . . . . . . . |  ##/.//.//.//.//.//..|  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Returning to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       You don't know where this place is...")
            mapMenu(12)
        elif travel == 4:
            print("||")
            print("||                       You don't know where this place is...")
            mapMenu(12)
        elif travel == 5:
            print("||")
            print("||                       You don't know where this place is...")
            mapMenu(12)
    elif nav == 13:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ##  ___             |  ## .___. . . . . . .|  ## .___. . . . . . .|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|         ")
        print("||         ## | 1 |  /`|       |  ##.| 2 |. . . . . . |  ##.| 3 |. . . . . . |  ##/| 4 |//.//.//.//.|  ##/| 5 |//.//.//.//.|         ")
        print("||         ##  ```` _\ |__     |  ## .```` . . . . . .|  ## .```` . . . . . .|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|         ")
        print("||         ##      /(   ( \    |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|         ")
        print("||         ##     /)|   /`(\   |  ## . . . . . . . . .|  ## . . . . . . . . .|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|         ")
        print("||         ##     \)|   | (/   |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Returning to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       You don't know where this place is...")
            mapMenu(13)
        elif travel == 5:
            print("||")
            print("||                       You don't know where this place is...")
            mapMenu(13)
    elif nav == 14:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ##  ___             |  ## .___. . . . . . .|  ## .___. . . . . . .|  ## .___. . . . . . .|  ##./___/.//.//.//.//|         ")
        print("||         ## | 1 |  /`|       |  ##.| 2 |. . . . . . |  ##.| 3 |. . . . . . |  ##.| 4 |. . . . . . |  ##/| 5 |//.//.//.//.|         ")
        print("||         ##  ```` _\ |__     |  ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|  ##/.```//.//.//.//./|         ")
        print("||         ##      /(   ( \    |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##.//.//.//.//.//.//|         ")
        print("||         ##     /)|   /`(\   |  ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|  ##//.//.//.//.//.//.|         ")
        print("||         ##     \)|   | (/   |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Returning to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       You don't know where this place is...")
            mapMenu(14)
    elif nav == 15:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ##  ___             |  ## .___. . . . . . .|  ## .___. . . . . . .|  ## .___. . . . . . .|  ## .___. . . . . . .|         ")
        print("||         ## | 1 |  /`|       |  ##.| 2 |. . . . . . |  ##.| 3 |. . . . . . |  ##.| 4 |. . . . . . |  ##.| 5 |. . . . . . |         ")
        print("||         ##  ```` _\ |__     |  ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|         ")
        print("||         ##      /(   ( \    |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |         ")
        print("||         ##     /)|   /`(\   |  ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|         ")
        print("||         ##     \)|   | (/   |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  || The Dark Depths ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Returning to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       Traveling to The Dark Depths...")
            return travel
    elif nav == 22:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##  ___             |  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |  /`|       |  ##/| 3 |//.//.//.//.|  ##/| 4 |//.//.//.//.|  ##/| 5 |//.//.//.//.|         ")
        print("||         ## .```` . . . . . .|  ##  ```` _\ |__     |  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|         ")
        print("||         ##. . . . . . . . . |  ##      /(   ( \    |  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|         ")
        print("||         ## . . . . . . . . .|  ##     /)|   /`(\   |  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|         ")
        print("||         ##. . . . . . . . . |  ##     \)|   | (/   |  ##/.//.//.//.//.//..|  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Returning to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(22)
        elif travel == 4:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(22)
        elif travel == 5:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(22)
    elif nav == 23:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##  ___             |  ## .___. . . . . . .|  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |  /`|       |  ##.| 3 |. . . . . . |  ##/| 4 |//.//.//.//.|  ##/| 5 |//.//.//.//.|         ")
        print("||         ## .```` . . . . . .|  ##  ```` _\ |__     |  ## .```` . . . . . .|  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|         ")
        print("||         ##. . . . . . . . . |  ##      /(   ( \    |  ##. . . . . . . . . |  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|         ")
        print("||         ## . . . . . . . . .|  ##     /)|   /`(\   |  ## . . . . . . . . .|  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|         ")
        print("||         ##. . . . . . . . . |  ##     \)|   | (/   |  ##. . . . . . . . . |  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Returning to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(23)
        elif travel == 5:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(23)
    elif nav == 24:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##  ___             |  ## .___. . . . . . .|  ## .___. . . . . . .|  ##./___/.//.//.//.//|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |  /`|       |  ##.| 3 |. . . . . . |  ##.| 4 |. . . . . . |  ##/| 5 |//.//.//.//.|         ")
        print("||         ## .```` . . . . . .|  ##  ```` _\ |__     |  ## .```` . . . . . .|  ## .```` . . . . . .|  ##/.```//.//.//.//./|         ")
        print("||         ##. . . . . . . . . |  ##      /(   ( \    |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##.//.//.//.//.//.//|         ")
        print("||         ## . . . . . . . . .|  ##     /)|   /`(\   |  ## . . . . . . . . .|  ## . . . . . . . . .|  ##//.//.//.//.//.//.|         ")
        print("||         ##. . . . . . . . . |  ##     \)|   | (/   |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Returning to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       You don't know where that place is...")
            MapMenu(24)
    elif nav == 25:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##  ___             |  ## .___. . . . . . .|  ## .___. . . . . . .|  ## .___. . . . . . .|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |  /`|       |  ##.| 3 |. . . . . . |  ##.| 4 |. . . . . . |  ##.| 5 |. . . . . . |         ")
        print("||         ## .```` . . . . . .|  ##  ```` _\ |__     |  ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|         ")
        print("||         ##. . . . . . . . . |  ##      /(   ( \    |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |         ")
        print("||         ## . . . . . . . . .|  ##     /)|   /`(\   |  ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|         ")
        print("||         ##. . . . . . . . . |  ##     \)|   | (/   |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  || The Dark Depths ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Returning to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       Traveling to The Dark Depths...")
            return travel
    elif nav == 33:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##. ___. . . . . . .|  ##  ___             |  ##./___/.//.//.//.//|  ##./___/.//.//.//.//|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |. . . . . . |  ## | 3 |  /`|       |  ##/| 4 |//.//.//.//.|  ##/| 5 |//.//.//.//.|         ")
        print("||         ## .```` . . . . . .|  ## .```` . . . . . .|  ##  ```  _\ |__     |  ##/.```//.//.//.//./|  ##/.```//.//.//.//./|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##      /(   ( \    |  ##.//.//.//.//.//.//|  ##.//.//.//.//.//.//|         ")
        print("||         ## . . . . . . . . .|  ## . . . . . . . . .|  ##     /)|   /`(\   |  ##//.//.//.//.//.//.|  ##//.//.//.//.//.//.|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##     \)|   | (/   |  ##/.//.//.//.//.//./|  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  ?  ?  ?  ?  ?  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Returning to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(33)
        elif travel == 5:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(33)
    elif nav == 34:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##. ___. . . . . . .|  ##  ___             |  ## .___. . . . . . .|  ##./___/.//.//.//.//|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |. . . . . . |  ## | 3 |  /`|       |  ##.| 4 |. . . . . . |  ##/| 5 |//.//.//.//.|         ")
        print("||         ## .```` . . . . . .|  ## .```` . . . . . .|  ##  ```  _\ |__     |  ## .```` . . . . . .|  ##/.```//.//.//.//./|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##      /(   ( \    |  ##. . . . . . . . . |  ##.//.//.//.//.//.//|         ")
        print("||         ## . . . . . . . . .|  ## . . . . . . . . .|  ##     /)|   /`(\   |  ## . . . . . . . . .|  ##//.//.//.//.//.//.|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##     \)|   | (/   |  ##. . . . . . . . . |  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Returning to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(34)
    elif nav == 35:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##. ___. . . . . . .|  ##  ___             |  ## .___. . . . . . .|  ## .___. . . . . . .|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |. . . . . . |  ## | 3 |  /`|       |  ##.| 4 |. . . . . . |  ##.| 5 |. . . . . . |         ")
        print("||         ## .```` . . . . . .|  ## .```` . . . . . .|  ##  ```  _\ |__     |  ## .```` . . . . . .|  ## .```` . . . . . .|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##      /(   ( \    |  ##. . . . . . . . . |  ##. . . . . . . . . |         ")
        print("||         ## . . . . . . . . .|  ## . . . . . . . . .|  ##     /)|   /`(\   |  ## . . . . . . . . .|  ## . . . . . . . . .|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##     \)|   | (/   |  ##. . . . . . . . . |  ##. . . . . . . . . |         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  || The Dark Depths ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Returning to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       Traveling to The Dark Depths...")
            return travel
    elif nav == 44:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##. ___. . . . . . .|  ## .___. . . . . . .|  ##  ___             |  ##./___/.//.//.//.//|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |. . . . . . |  ##.| 3 |. . . . . . |  ## | 4 |  /`|       |  ##/| 5 |//.//.//.//.|         ")
        print("||         ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|  ##  ```` _\ |__     |  ##/.```//.//.//.//./|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##      /(   ( \    |  ##.//.//.//.//.//.//|         ")
        print("||         ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|  ##     /)|   /`(\   |  ##//.//.//.//.//.//.|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##     \)|   | (/   |  ##/.//.//.//.//.//./|         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  ||  ?  ?  ?  ?  ?  ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Returning to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       You don't know where that place is...")
            mapMenu(44)
    elif nav == 45:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##. ___. . . . . . .|  ## .___. . . . . . .|  ##  ___             |  ## .___. . . . . . .|         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |. . . . . . |  ##.| 3 |. . . . . . |  ## | 4 |  /`|       |  ##.| 5 |. . . . . . |         ")
        print("||         ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|  ##  ```` _\ |__     |  ## .```` . . . . . .|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##      /(   ( \    |  ##. . . . . . . . . |         ")
        print("||         ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|  ##     /)|   /`(\   |  ## . . . . . . . . .|         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##     \)|   | (/   |  ##. . . . . . . . . |         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  || The Dark Depths ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Returning to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       Traveling to The Dark Depths...")
            return travel
    elif nav == 55:
        border()
        print("||                                                                                                                                   ")
        print("||          ___________________    ___________________    ___________________    ___________________    ___________________          ")
        print("||         ## .___. . . . . . .|  ##. ___. . . . . . .|  ## .___. . . . . . .|  ## .___. . . . . . .|  ##  ___             |         ")
        print("||         ##.| 1 |. . . . . . |  ## | 2 |. . . . . . |  ##.| 3 |. . . . . . |  ##.| 4 |. . . . . . |  ## | 5 |  /`|       |         ")
        print("||         ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|  ## .```` . . . . . .|  ##  ```` _\ |__     |         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##      /(   ( \    |         ")
        print("||         ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|  ## . . . . . . . . .|  ##     /)|   /`(\   |         ")
        print("||         ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##. . . . . . . . . |  ##     \)|   | (/   |         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        print("||         || Petrified Woods ||  ||  City  Streets  ||  ||  Deep Dungeons  ||  ||  Church Crypts  ||  || The Dark Depths ||         ")
        print("||         #####################  #####################  #####################  #####################  #####################         ")
        border()
        travel = int(input("||                 Where would you like to go?         : "))
        if travel == 1:
            print("||")
            print("||                       Traveling to Petrified Woods...")
            return travel
        elif travel == 2:
            print("||")
            print("||                       Traveling to City Streets...")
            return travel
        elif travel == 3:
            print("||")
            print("||                       Traveling to Deep Dungeons...")
            return travel
        elif travel == 4:
            print("||")
            print("||                       Traveling to Church Crypts...")
            return travel
        elif travel == 5:
            print("||")
            print("||                       Returning to The Dark Depths...")
            return travel

def mapMenu(player):
    location = player.location
    if location == 11 or location == 12 or location == 13 or location == 14 or location == 15:
        print(str("                              _________________________ ").center(140))
        print(str(" __________________________  |                         |").center(140))
        print(str("|     Current Location     |=|     Petrified Woods     |").center(140))
        print(str(" ``````````````````````````  |_________________________|").center(140))
        if location == 11:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").center(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 12:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 13:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 14:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
            print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
            print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
            print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
            print(str("                         | in agitated delerium.                          |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 15:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
            print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
            print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
            print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
            print(str("                         | in agitated delerium.                          |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|  The Ministry  |=| The epicenter of the plague, profane research  |").center(140))
            print(str(" ```   ````````````````  | was performed here. The visage of traumatic    |").center(140))
            print(str("                         | experiments still echo through the halls,      |").center(140))
            print(str("                         | accompanied by the cries of the patients left  |").center(140))
            print(str("                         | behind.                                        |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
    elif location == 22 or location == 23 or location == 24 or location == 25:
        print(str("                              _________________________ ").center(140))
        print(str(" __________________________  |                         |").center(140))
        print(str("|     Current Location     |=|      Sable Streets      |").center(140))
        print(str(" ``````````````````````````  |_________________________|").center(140))
        if location == 22:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 23:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 24:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
            print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
            print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
            print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
            print(str("                         | in agitated delerium.                          |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 25:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
            print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
            print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
            print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
            print(str("                         | in agitated delerium.                          |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|  The Ministry  |=| The epicenter of the plague, profane research  |").center(140))
            print(str(" ```   ````````````````  | was performed here. The visage of traumatic    |").center(140))
            print(str("                         | experiments still echo through the halls,      |").center(140))
            print(str("                         | accompanied by the cries of the patients left  |").center(140))
            print(str("                         | behind.                                        |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
    elif location == 33 or location == 34 or location == 35:
        print(str("                              _________________________ ").center(140))
        print(str(" __________________________  |                         |").center(140))
        print(str("|     Current Location     |=|      Deep Dungeons      |").center(140))
        print(str(" ``````````````````````````  |_________________________|").center(140))
        if location == 33:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 34:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
            print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
            print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
            print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
            print(str("                         | in agitated delerium.                          |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 35:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
            print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
            print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
            print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
            print(str("                         | in agitated delerium.                          |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|  The Ministry  |=| The epicenter of the plague, profane research  |").center(140))
            print(str(" ```   ````````````````  | was performed here. The visage of traumatic    |").center(140))
            print(str("                         | experiments still echo through the halls,      |").center(140))
            print(str("                         | accompanied by the cries of the patients left  |").center(140))
            print(str("                         | behind.                                        |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
    elif location == 44 or location == 45:
        print(str("                              _________________________ ").center(140))
        print(str(" __________________________  |                         |").center(140))
        print(str("|     Current Location     |=|     Profane Crypts      |").center(140))
        print(str(" ``````````````````````````  |_________________________|").center(140))
        if location == 44:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|     ? ? ?      |=|     You haven't discovered this place yet.     |").center(140))
            print(str(" ```   ````````````````   ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
        elif location == 45:
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
            print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
            print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
            print(str("                         | to reflect the inhospitable nature of the      |").center(140))
            print(str("                         | wodos.                                         |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 2 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
            print(str(" ```   ````````````````  |  While the average citizen has locked himself  |").center(140))
            print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
            print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 3 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
            print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
            print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
            print(str("                         | strange practitioners came here with wild      |").center(140))
            print(str("                         | experiments and unfettered access to subjects. |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" ___   ________________   ________________________________________________ ").center(140))
            print(str("| 4 |=|  The Ministry  |=| The epicenter of the plague, profane research  |").center(140))
            print(str(" ```   ````````````````  | was performed here. The visage of traumatic    |").center(140))
            print(str("                         | experiments still echo through the halls,      |").center(140))
            print(str("                         | accompanied by the cries of the patients left  |").center(140))
            print(str("                         | behind.                                        |").center(140))
            print(str("                          ```````````````````````````````````````````````` ").center(140))
            print(str(" _________________________________________ ").center(140))
            print(str("|                                         |").center(140))
            print(str("|     Where would you like to travel?     |").cemter(140))
            print(str("|             ________________            |").center(140))
            print(str("|            | 5 |   Cancel   |           |").center(140))
            print(str("|             ````````````````            |").center(140))
            print(str("|_________________________________________|").center(140))
            print("")
            travel = input(str(":  ").center(140))
    elif location == 55:
        print(str("                              _________________________ ").center(140))
        print(str(" __________________________  |                         |").center(140))
        print(str("|     Current Location     |=|   Ministry of Medicine  |").center(140))
        print(str(" ``````````````````````````  |_________________________|").center(140))
        print(str(" ___   ________________   ________________________________________________ ").center(140))
        print(str("| 1 |=|Petrified Woods |=| An ancient wood with trees older than any      |").center(140))
        print(str(" ```   ````````````````  | kingdom of man. They are unchanging, becoming  |").center(140))
        print(str("                         | stone long ago. The wildlife here has adapted  |").center(140))
        print(str("                         | to reflect the inhospitable nature of the      |").center(140))
        print(str("                         | wodos.                                         |").center(140))
        print(str("                          ```````````````````````````````````````````````` ").center(140))
        print(str(" ___   ________________   ________________________________________________ ").center(140))
        print(str("| 2 |=| Sable Streets  |=|  Dark streets are home to nefarious denizens.  |").center(140))
        print(str(" ```   ````````````````  |  While the good citizen has locked himself     |").center(140))
        print(str("                         |  away in his home, fearing infection, thugs    |").center(140))
        print(str("                         |  and anarchists lay claim to everything else.  |").center(140))
        print(str("                          ```````````````````````````````````````````````` ").center(140))
        print(str(" ___   ________________   ________________________________________________ ").center(140))
        print(str("| 3 |=| Deep Dungeons  |=| An over-crowded prison complex was introduced  |").center(140))
        print(str(" ```   ````````````````  | to a new kind of horror when the plague seeped |").center(140))
        print(str("                         | into the cells. Abandoned and left to mutate,  |").center(140))
        print(str("                         | strange practitioners came here with wild      |").center(140))
        print(str("                         | experiments and unfettered access to subjects. |").center(140))
        print(str("                          ```````````````````````````````````````````````` ").center(140))
        print(str(" ___   ________________   ________________________________________________ ").center(140))
        print(str("| 3 |=| Furtive Crypts |=| According to public record, these crypts were  |").center(140))
        print(str(" ```   ````````````````  | not meant to exist. The church had many secrets|").center(140))
        print(str("                         | and most were hidden here. Creatures, neither  |").center(140))
        print(str("                         | beast nor man, rest in tombs. Some still wander|").center(140))
        print(str("                         | in agitated delerium.                          |").center(140))
        print(str("                          ```````````````````````````````````````````````` ").center(140))
        print(str(" _________________________________________ ").center(140))
        print(str("|                                         |").center(140))
        print(str("|     Where would you like to travel?     |").cemter(140))
        print(str("|             ________________            |").center(140))
        print(str("|            | 5 |   Cancel   |           |").center(140))
        print(str("|             ````````````````            |").center(140))
        print(str("|_________________________________________|").center(140))
        print("")
        travel = input(str(":  ").center(140))
 



